//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Citas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Citas()
        {
            this.Facturas = new HashSet<Facturas>();
        }
    
        public int Id_Cita { get; set; }
        public System.DateTime Fecha_Cita { get; set; }
        public System.TimeSpan Hora_Cita { get; set; }
        public string Id_Usuario { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Serv_Prod { get; set; }
        public bool Estado { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Empleados Empleados { get; set; }
        public virtual Servicios_Productos Servicios_Productos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
    }
}
