//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Ganancias_Facturas
    {
        public int Id_Factura_Ganancias { get; set; }
        public int Id_Factura { get; set; }
        public int Id_Ganancia { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual GananciaDiaria GananciaDiaria { get; set; }
    }
}
