//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Factura_Productos
    {
        public int Id_Detalle { get; set; }
        public Nullable<int> Id_Factura { get; set; }
        public int Id_Producto { get; set; }
        public int Cantidad { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Servicios_Productos Servicios_Productos { get; set; }
    }
}
