//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class GananciaDiaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GananciaDiaria()
        {
            this.Detalle_Ganancias_Facturas = new HashSet<Detalle_Ganancias_Facturas>();
        }

        [Display(Name = "ID de Ganancias")]
        public int Id_Ganancias { get; set; }

        [Display(Name = "Ingresos")]
        public decimal Ingresos { get; set; }

        [Display(Name = "Fecha de Ganancias")]
        public DateTime Fecha { get; set; }
        public Nullable<decimal> Egresos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Ganancias_Facturas> Detalle_Ganancias_Facturas { get; set; }
    }
}
