//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ImagenesEmpleados
    {
        [Display(Name = "ID")]
        public int Id { get; set; }

        [Display(Name = "ID de Empleado")]
        public int Id_Empleado { get; set; }

        [Display(Name = "Nombre del Archivo")]
        public string FileName { get; set; }

        [Display(Name = "Datos de la Imagen")]
        public byte[] ImageData { get; set; }

        public virtual Empleados Empleados { get; set; }
    }
}
