//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImagenesPromosServ
    {
        public int Id { get; set; }
        public int Id_Promo_Servicio { get; set; }
        public string FileName { get; set; }
        public byte[] ImageData { get; set; }
    
        public virtual PromocionesServicios PromocionesServicios { get; set; }
    }
}
