//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Planilla
    {
        [Display(Name = "ID de Planilla")]
        public int Id_Planilla { get; set; }

        [Display(Name = "Fecha de Ingreso")]
        public DateTime Fecha_Ingreso { get; set; }

        [Display(Name = "Salario")]
        public decimal Salario { get; set; }

        [Display(Name = "Especialización")]
        public string Especializacion { get; set; }

        [Display(Name = "ID de Empleado")]
        public int Id_Empleado { get; set; }

        public virtual Empleados Empleados { get; set; }
    }
}
