//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planilla
    {
        public int Id_Planilla { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public decimal Salario { get; set; }
        public string Especializacion { get; set; }
        public int Id_Empleado { get; set; }
    
        public virtual Empleados Empleados { get; set; }
    }
}
