//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PromocionesProductos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PromocionesProductos()
        {
            this.DetalleFacturaPromProdu = new HashSet<DetalleFacturaPromProdu>();
            this.ImagenesPromosProd = new HashSet<ImagenesPromosProd>();
        }
    
        public int Id_Promo_Producto { get; set; }
        public string Nombre_Promo_Producto { get; set; }
        public string Descripcion_Promo_Producto { get; set; }
        public decimal Precio_Nuevo_Producto { get; set; }
        public System.DateTime Fecha_Inicio_Promo { get; set; }
        public System.DateTime Fecha_Final_Promo { get; set; }
        public int Id_Producto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleFacturaPromProdu> DetalleFacturaPromProdu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImagenesPromosProd> ImagenesPromosProd { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
