//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reseñas
    {
        [Display(Name = "ID de Reseña")]
        public int Id_Resena { get; set; }

        [Display(Name = "Comentario")]
        public string Comentario { get; set; }

        [Display(Name = "Calificación")]
        public byte? Calificacion { get; set; }

        [Display(Name = "ID de Usuario")]
        public string Id_Usuario { get; set; }

        public virtual AspNetUsers AspNetUsers { get; set; }
    }
}
